## Imports

In [85]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import (
    StandardScaler,
    PowerTransformer,
    OrdinalEncoder,
    LabelEncoder
)

from sklearn.impute import SimpleImputer

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

## Data

In [86]:
X = pd.read_csv("smartphone_battery_features.csv")
y = pd.read_csv("smartphone_battery_targets.csv")

print(X.shape)
print(y.shape)

(5000, 15)
(5000, 3)

In [87]:
df = pd.merge(X, y, on="Device_ID")

df.head()

,Device_ID,device_age_months,battery_capacity_mah,avg_screen_on_hours_per_day,avg_charging_cycles_per_week,avg_battery_temp_celsius,fast_charging_usage_percent,overnight_charging_freq_per_week,gaming_hours_per_week,video_streaming_hours_per_week,background_app_usage_level,signal_strength_avg,charging_habit_score,usage_intensity_score,thermal_stress_index,current_battery_health_percent,recommended_action
0,207dd94c-0430-43aa-b388-4893447e628e,38,4500,7.1,11.4,34.8,90.8,7,7.9,14.0,Medium,Poor,4,10.0,4.04,32.8,Change Phone
1,3f4d1d33-ba89-4814-a168-7b4cc75be26b,28,3000,6.8,10.3,35.4,60.6,2,8.6,11.0,Medium,Good,7,10.0,4.23,50.3,Replace Battery
2,b4adca05-564f-4b70-ab69-e8d66e656463,14,3000,7.2,11.2,29.4,29.3,4,0.3,10.3,Medium,Good,6,10.0,2.21,66.1,Replace Battery
3,4147e039-31b7-480a-bbc9-03cd0f66e9f1,42,3000,5.5,8.3,32.8,62.5,0,1.9,4.9,Medium,Good,8,10.0,3.13,46.8,Change Phone
4,3f9b0fb7-73c2-4ab7-8e30-7b492097a3f5,7,3000,7.6,11.6,38.7,85.4,6,7.9,9.3,High,Good,5,10.0,4.95,67.2,Replace Battery

In [88]:
drop_cols = [
    "thermal_stress_index",
    "avg_charging_cycles_per_week",
    "charging_habit_score",
    "Device_ID"
]

df = df.drop(columns=drop_cols)

In [89]:
y_reg = df["current_battery_health_percent"]

label_encoder = LabelEncoder()
y_clf = label_encoder.fit_transform(df["recommended_action"])

X = df.drop(
    columns=[
        "current_battery_health_percent",
        "recommended_action"
    ]
)

## split

In [90]:
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X,
    y_reg,
    test_size=0.2,
    random_state=42
)

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X,
    y_clf,
    test_size=0.2,
    random_state=42,
    stratify=y_clf
)

In [91]:
numeric_cols = X.select_dtypes(include="number").columns
categorical_cols = X.select_dtypes(exclude="number").columns

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder())
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_cols),
    ("cat", categorical_pipeline, categorical_cols)
])

## reg model

In [92]:
from sklearn.ensemble import GradientBoostingRegressor

reg_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", GradientBoostingRegressor(
        random_state=42
    ))
])

reg_model.fit(X_train_r, y_train_r)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['device_age_months', 'battery_capacity_mah',
       'avg_screen_on_hours_per_day', 'avg_battery_temp_celsius',
       'fast_charging_usage_percent', 'overnight_charging_freq_per_week',
       'gaming_hours_per_week', 'video_streaming_hours_per_week',
       'usage_intensity_score'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder())]),
                                                  Index(['background_app_usage_level', 'signal_strength_avg'], dtype='object'))])),
                ('model', GradientBoostingRegressor(random_state=42))])

In [93]:
pred = reg_model.predict(X_test_r)

mae = mean_absolute_error(y_test_r, pred)
rmse = np.sqrt(mean_squared_error(y_test_r, pred))
r2 = r2_score(y_test_r, pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 3.285933354462162
RMSE: 4.172614274952063
R2: 0.9443937077276937

## clf model

In [94]:
from sklearn.ensemble import GradientBoostingClassifier

clf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", GradientBoostingClassifier(
        random_state=42
    ))
])

clf_model.fit(X_train_c, y_train_c)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['device_age_months', 'battery_capacity_mah',
       'avg_screen_on_hours_per_day', 'avg_battery_temp_celsius',
       'fast_charging_usage_percent', 'overnight_charging_freq_per_week',
       'gaming_hours_per_week', 'video_streaming_hours_per_week',
       'usage_intensity_score'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder())]),
                                                  Index(['background_app_usage_level', 'signal_strength_avg'], dtype='object'))])),
                ('model', GradientBoostingClassifier(random_state=42))])

In [96]:
pred = clf_model.predict(X_test_c)

acc = accuracy_score(y_test_c, pred)
f1 = f1_score(y_test_c, pred, average="weighted")

print("Accuracy:", acc)
print("F1 score:", f1)

Accuracy: 0.871
F1 score: 0.8711316467559695

## compare several models

In [95]:
models = {
    "Linear": LinearRegression(),
    "Ridge": Ridge(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42)
}

results = []

for name, model in models.items():

    pipe = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])

    pipe.fit(X_train_r, y_train_r)

    pred = pipe.predict(X_test_r)

    results.append([
        name,
        r2_score(y_test_r, pred)
    ])

pd.DataFrame(results, columns=["Model", "R2"])

               Model        R2
0             Linear  0.914075
1              Ridge  0.914073
2      Decision Tree  0.871052
3      Random Forest  0.940472
4  Gradient Boosting  0.944394

In [97]:
!pip install mlflow

Requirement already satisfied: mlflow in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.13.0)
Requirement already satisfied: mlflow-skinny==3.13.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (3.13.0)
Requirement already satisfied: mlflow-tracing==3.13.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (3.13.0)
Requirement already satisfied: Flask-CORS<7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (6.0.2)
Requirement already satisfied: Flask<4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (3.14.0)
Requirement already satisfied: alembic!=1.10.0,<2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (1.17.2)
Requirement already satisfied: cryptography<49,>=43.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (48.0.0)
Requirement already satisfied: docker<8,>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<27 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (26.0.0)
Requirement already satisfied: huey<4,>=2.5.4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (3.0.1)
Requirement already satisfied: matplotlib<4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (1.26.4)
Requirement already satisfied: pandas<3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (2.3.0)
Requirement already satisfied: pyarrow<25,>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (23.0.0)
Requirement already satisfied: scikit-learn<2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (1.7.1)
Requirement already satisfied: scipy<2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (1.16.1)
Requirement already satisfied: skops<1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (2.0.45)
Requirement already satisfied: cachetools<8,>=5.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (0.114.0)
Requirement already satisfied: fastapi<1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (0.136.3)
Requirement already satisfied: gitpython<4,>=3.1.9 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (9.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (1.42.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (1.42.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (1.42.1)
Requirement already satisfied: packaging<27 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (25.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (6.33.4)
Requirement already satisfied: pydantic<3,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (2.12.5)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (1.2.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.13.0->mlflow) (0.48.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from aiohttp<4->mlflow) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from aiohttp<4->mlflow) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from aiohttp<4->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from aiohttp<4->mlflow) (1.24.2)
Requirement already satisfied: Mako in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: cffi>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from cryptography<49,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: google-auth~=2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (2.53.0)
Requirement already satisfied: urllib3>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from Flask<4->mlflow) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from Flask<4->mlflow) (3.1.5)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (5.0.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.13.0->mlflow) (4.1.0)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (1.4.8)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (3.2.3)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.13.0->mlflow) (0.63b1)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (2.41.5)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (2026.1.4)
Requirement already satisfied: joblib>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn<2->mlflow) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: anyio<5,>=3.6.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from starlette<2->mlflow-skinny==3.13.0->mlflow) (4.9.0)
Requirement already satisfied: sniffio>=1.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from anyio<5,>=3.6.2->starlette<2->mlflow-skinny==3.13.0->mlflow) (1.3.1)
Requirement already satisfied: h11>=0.8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from uvicorn<1->mlflow-skinny==3.13.0->mlflow) (0.16.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography<49,>=43.0.0->mlflow) (2.22)
Requirement already satisfied: wcwidth in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from prettytable>=3.9->skops<1->mlflow) (0.2.13)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.6.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [101]:
models = {
    "Linear": LinearRegression(),
    "RandomForest": RandomForestRegressor(),
    "GradientBoosting": GradientBoostingRegressor()
}

In [105]:
import mlflow

mlflow.set_experiment("Battery Health Regression")

2026/06/04 22:10:06 INFO mlflow.tracking.fluent: Experiment with name 'Battery Health Regression' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/2', creation_time=1780593006770, effective_trace_archival_retention=None, experiment_id='2', last_update_time=1780593006770, lifecycle_stage='active', name='Battery Health Regression', tags={}, trace_location=None, workspace='default'>

In [106]:
for name, model in models.items():

    with mlflow.start_run(run_name=name):

        pipe = Pipeline([
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipe.fit(X_train_r, y_train_r)

        pred = pipe.predict(X_test_r)

        r2 = r2_score(y_test_r, pred)

        mlflow.log_param("model", name)
        mlflow.log_metric("r2", r2)

        mlflow.sklearn.log_model(
            pipe,
            "model"
        )

2026/06/04 22:10:27 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/06/04 22:10:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run Linear at: http://127.0.0.1:5000/#/experiments/2/runs/d699bfd10f3041f0a91680f5290cd1a9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

2026/06/04 22:10:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/06/04 22:10:29 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RandomForest at: http://127.0.0.1:5000/#/experiments/2/runs/bfd3b39bf5bc4110b6ad84aa5490a305
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

2026/06/04 22:10:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/06/04 22:10:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run GradientBoosting at: http://127.0.0.1:5000/#/experiments/2/runs/41107d89f9ba4323948c7f02c322895a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

In [107]:
for exp in mlflow.search_experiments():
    print(exp.name)

Battery Health Regression
genai-retention-regression
Default